export const PRICING_TIERS = Object.freeze([
  {
    id: "free",
    name: "Free",
    monthlyPrice: 0,
    annualPrice: 0,
    creditsPerMonth: 3,
    storageQuotaMb: 500,
    features: {
      hasWatermark: true,
      maxResolution: "720p",
      voiceOptions: "basic" as const,
      hasPrioritySupport: false,
    },
  },
  {
    id: "basic",
    name: "Basic",
    monthlyPrice: 2900,
    annualPrice: 28900,
    creditsPerMonth: 30,
    storageQuotaMb: 5120,
    features: {
      hasWatermark: false,
      maxResolution: "1080p",
      voiceOptions: "basic" as const,
      hasPrioritySupport: false,
    },
  },
  {
    id: "pro",
    name: "Pro",
    monthlyPrice: 7900,
    annualPrice: 78900,
    creditsPerMonth: 100,
    storageQuotaMb: 20480,
    features: {
      hasWatermark: false,
      maxResolution: "1080p",
      voiceOptions: "all" as const,
      hasPrioritySupport: true,
    },
  },
  {
    id: "enterprise",
    name: "Enterprise",
    monthlyPrice: 0,
    annualPrice: 0,
    creditsPerMonth: 999,
    storageQuotaMb: 102400,
    features: {
      hasWatermark: false,
      maxResolution: "1080p",
      voiceOptions: "all" as const,
      hasPrioritySupport: true,
    },
  },
] as const);
