export const ERROR_CODES = {
  // Auth
  AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",
  AUTH_FORBIDDEN: "AUTH_FORBIDDEN",
  AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",

  // Validation
  VALIDATION_FAILED: "VALIDATION_FAILED",
  VALIDATION_INVALID_INPUT: "VALIDATION_INVALID_INPUT",
  VALIDATION_MISSING_FIELD: "VALIDATION_MISSING_FIELD",

  // Credits
  CREDIT_INSUFFICIENT: "CREDIT_INSUFFICIENT",
  CREDIT_RESERVATION_FAILED: "CREDIT_RESERVATION_FAILED",

  // Generation
  GENERATION_SCRIPT_FAILED: "GENERATION_SCRIPT_FAILED",
  GENERATION_IMAGE_FAILED: "GENERATION_IMAGE_FAILED",
  GENERATION_AUDIO_FAILED: "GENERATION_AUDIO_FAILED",
  GENERATION_TIMEOUT: "GENERATION_TIMEOUT",

  // Rendering
  RENDER_FAILED: "RENDER_FAILED",
  RENDER_TIMEOUT: "RENDER_TIMEOUT",
  RENDER_SERVICE_UNAVAILABLE: "RENDER_SERVICE_UNAVAILABLE",

  // Storage
  STORAGE_UPLOAD_FAILED: "STORAGE_UPLOAD_FAILED",
  STORAGE_QUOTA_EXCEEDED: "STORAGE_QUOTA_EXCEEDED",
  STORAGE_FILE_NOT_FOUND: "STORAGE_FILE_NOT_FOUND",

  // External
  EXTERNAL_API_ERROR: "EXTERNAL_API_ERROR",
  EXTERNAL_RATE_LIMITED: "EXTERNAL_RATE_LIMITED",
  EXTERNAL_TIMEOUT: "EXTERNAL_TIMEOUT",

  // Resources
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  RESOURCE_CONFLICT: "RESOURCE_CONFLICT",
  RESOURCE_GONE: "RESOURCE_GONE",

  // Stripe / Billing
  STRIPE_WEBHOOK_INVALID: "STRIPE_WEBHOOK_INVALID",
  STRIPE_CHECKOUT_FAILED: "STRIPE_CHECKOUT_FAILED",
  SUBSCRIPTION_NOT_FOUND: "SUBSCRIPTION_NOT_FOUND",
  SUBSCRIPTION_ALREADY_PAID: "SUBSCRIPTION_ALREADY_PAID",

  // Internal
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
